# Generated by Django 4.2.6 on 2023-11-01 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activate_Token',
            new_name='UserToken',
        ),
    ]
