# Generated by Django 4.2.6 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
