name: Deploy Django App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:

    - name: Install sshpass
      run: |
        sudo apt update
        sudo apt install -y sshpass
    
    - name: Adding ssh-key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Pull latest changes
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        git pull
        EOF

    - name: Install Python dependencies
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        ${{secrets.INSTALL_PYTHON_DEPENDENCIES}}
        EOF
    
    - name: Copying Virtual Environment
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        rm -rf .env
        echo 'DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"' >> .env
        echo 'ROBO_FLOW_API_URL="${{ secrets.ROBO_FLOW_API_URL }}"' >> .env
        echo 'EMAIL_HOST="${{ secrets.EMAIL_HOST }}"' >> .env
        echo 'EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}"' >> .env
        echo 'EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}"' >> .env
        echo 'DEFAULT_FROM_EMAIL="${{ secrets.DEFAULT_FROM_EMAIL }}"' >> .env
        EOF
    
    - name: Migrate Database && Collect Static Files
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        ${{ secrets.MIGRATE_DATABASE }}
        EOF
        
    - name: Restart WSGI server (Gunicorn)
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        devil www restart api.smartkrishi.me
        EOF